apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ cookiecutter.project_shortname }}
  namespace: {{ cookiecutter.project_shortname }}
spec:
  targetNamespace: {{ cookiecutter.project_shortname }}-staging
  install:
    createNamespace: true
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    replicaCount: 2
