apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: app
  namespace: app
spec:
  targetNamespace: app-production
  install:
    createNamespace: true
  chart:
    spec:
      version: ">=1.0.0"
  values:
    replicaCount: 2
